CXX = g++
CXXFLAGS = -o
FILES = Comparison.cpp SortedComparison.cpp main.cpp
OUT_EXE = comparator.exe

build: $(FILES)
		$(CXX) $(CXXFLAGS) $(OUT_EXE) $(FILES)

clean:
		rm -f *.o core

rebulid: clean build
